services:
  bg-remover:
    build: .
    environment:
      BG_MODEL: ${BG_MODEL:-birefnet-general}
      BG_CPU_MEM_ARENA: ${BG_CPU_MEM_ARENA:-1}
    #ports:
    #  - "${EXTERNAL_PORT}:8000"
    volumes:
      - ./model_data:/root/.u2net
    restart: always

volumes:
  model_data: